# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: CI
description: Shipfox continuous integration pipeline

inputs:
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
