import {SiGitlab} from '@icons-pack/react-simple-icons';
import {
  ActivityLogIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CalendarIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretSortIcon,
  CaretUpIcon,
  CheckCircledIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  CommitIcon,
  Cross2Icon,
  CrossCircledIcon,
  CrumpledPaperIcon,
  DesktopIcon,
  DotFilledIcon,
  DotIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DoubleArrowDownIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DoubleArrowUpIcon,
  EnterIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  EyeClosedIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  GearIcon,
  GitHubLogoIcon,
  HamburgerMenuIcon,
  LapTimerIcon,
  LayersIcon,
  LightningBoltIcon,
  Link1Icon,
  Link2Icon,
  MagnifyingGlassIcon,
  MinusCircledIcon,
  MinusIcon,
  MoonIcon,
  OpenInNewWindowIcon,
  PaperPlaneIcon,
  PlusCircledIcon,
  PlusIcon,
  ReloadIcon,
  RowsIcon,
  SizeIcon,
  StackIcon,
  StopwatchIcon,
  SunIcon,
  TrashIcon,
} from '@radix-ui/react-icons';
import {
  BookIcon,
  BookMarkedIcon,
  DollarSignIcon,
  EuroIcon,
  GitBranchIcon,
  HandCoinsIcon,
  Loader2,
  PiggyBankIcon,
  SnowflakeIcon,
} from 'lucide-react';
import type {ComponentType} from 'react';
import {cn} from 'utils';

export const Icons = {
  spinner: Loader2,
  repository: BookMarkedIcon,
  branch: GitBranchIcon,
  commit: CommitIcon,
  github: GitHubLogoIcon,
  gitlab: SiGitlab,
  reload: ReloadIcon,
  sun: SunIcon,
  moon: MoonIcon,
  desktop: DesktopIcon,
  chevronUp: ChevronUpIcon,
  chevronRight: ChevronRightIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  arrowUp: ArrowUpIcon,
  arrowRight: ArrowRightIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  doubleArrowUp: DoubleArrowUpIcon,
  doubleArrowRight: DoubleArrowRightIcon,
  doubleArrowDown: DoubleArrowDownIcon,
  doubleArrowLeft: DoubleArrowLeftIcon,
  caretUp: CaretUpIcon,
  caretRight: CaretRightIcon,
  caretDown: CaretDownIcon,
  caretLeft: CaretLeftIcon,
  caretSort: CaretSortIcon,
  check: CheckIcon,
  eyeOpen: EyeOpenIcon,
  eyeClosed: EyeClosedIcon,
  eyeNone: EyeNoneIcon,
  calendar: CalendarIcon,
  cross: Cross2Icon,
  dot: DotIcon,
  dotFilled: DotFilledIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  checkCircled: CheckCircledIcon,
  crossCircled: CrossCircledIcon,
  stopwatch: StopwatchIcon,
  lapTimer: LapTimerIcon,
  lightningBolt: LightningBoltIcon,
  layers: LayersIcon,
  stack: StackIcon,
  rows: RowsIcon,
  activityLog: ActivityLogIcon,
  size: SizeIcon,
  openInNewWindow: OpenInNewWindowIcon,
  crumpledPaper: CrumpledPaperIcon,
  snowflake: SnowflakeIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  plusCircled: PlusCircledIcon,
  minusCircled: MinusCircledIcon,
  gear: GearIcon,
  dotsHorizontal: DotsHorizontalIcon,
  dotsVertical: DotsVerticalIcon,
  paperPlane: PaperPlaneIcon,
  envelopeOpen: EnvelopeOpenIcon,
  envelopeClosed: EnvelopeClosedIcon,
  enter: EnterIcon,
  exit: ExitIcon,
  piggyBank: PiggyBankIcon,
  handCoins: HandCoinsIcon,
  clipboardCopy: ClipboardCopyIcon,
  clipboard: ClipboardIcon,
  trash: TrashIcon,
  hamburgerMenu: HamburgerMenuIcon,
  link1: Link1Icon,
  link2: Link2Icon,
  exclamationTriangle: ExclamationTriangleIcon,
  dollar: DollarSignIcon,
  usd: DollarSignIcon,
  euro: EuroIcon,
  eur: EuroIcon,
  book: BookIcon,
};

export type IconName = keyof typeof Icons;

export interface IconProps {
  icon: IconName;
  className?: string;
}

export function Icon({icon, className, ...props}: IconProps) {
  const Icon = Icons[icon] as ComponentType<Omit<IconProps, 'icon'>>;
  return <Icon className={cn(['h-4 w-4', className])} {...props} />;
}
