export const primitiveColors = {
  neutral: {
    variants: [
      'bg-neutral-0',
      'bg-neutral-50',
      'bg-neutral-100',
      'bg-neutral-200',
      'bg-neutral-300',
      'bg-neutral-400',
      'bg-neutral-500',
      'bg-neutral-600',
      'bg-neutral-700',
      'bg-neutral-800',
      'bg-neutral-900',
      'bg-neutral-950',
      'bg-neutral-1000',
    ],
  },
  purple: {
    variants: [
      'bg-purple-50',
      'bg-purple-100',
      'bg-purple-200',
      'bg-purple-300',
      'bg-purple-400',
      'bg-purple-500',
      'bg-purple-600',
      'bg-purple-700',
      'bg-purple-800',
      'bg-purple-900',
      'bg-purple-950',
    ],
  },
  blue: {
    variants: [
      'bg-blue-50',
      'bg-blue-100',
      'bg-blue-200',
      'bg-blue-300',
      'bg-blue-400',
      'bg-blue-500',
      'bg-blue-600',
      'bg-blue-700',
      'bg-blue-800',
      'bg-blue-900',
      'bg-blue-950',
    ],
  },
  green: {
    variants: [
      'bg-green-50',
      'bg-green-100',
      'bg-green-200',
      'bg-green-300',
      'bg-green-400',
      'bg-green-500',
      'bg-green-600',
      'bg-green-700',
      'bg-green-800',
      'bg-green-900',
      'bg-green-950',
    ],
  },
  primary: {
    variants: [
      'bg-primary-50',
      'bg-primary-100',
      'bg-primary-200',
      'bg-primary-300',
      'bg-primary-400',
      'bg-primary-500',
      'bg-primary-600',
      'bg-primary-700',
      'bg-primary-800',
      'bg-primary-900',
      'bg-primary-950',
    ],
  },
  red: {
    variants: [
      'bg-red-50',
      'bg-red-100',
      'bg-red-200',
      'bg-red-300',
      'bg-red-400',
      'bg-red-500',
      'bg-red-600',
      'bg-red-700',
      'bg-red-800',
      'bg-red-900',
      'bg-red-950',
    ],
  },
  orange: {
    variants: [
      'bg-orange-50',
      'bg-orange-100',
      'bg-orange-200',
      'bg-orange-300',
      'bg-orange-400',
      'bg-orange-500',
      'bg-orange-600',
      'bg-orange-700',
      'bg-orange-800',
      'bg-orange-900',
      'bg-orange-950',
    ],
  },
  accent: {
    variants: [
      'bg-accent-purple',
      'bg-accent-indigo',
      'bg-accent-mint',
      'bg-accent-green',
      'bg-accent-teal',
      'bg-accent-brown',
      'bg-accent-blue',
      'bg-accent-orange',
      'bg-accent-yellow',
      'bg-accent-pink',
      'bg-accent-gray',
      'bg-accent-cyan',
      'bg-accent-red',
    ],
  },
  'alpha-white': {
    variants: [
      'bg-alpha-white-0',
      'bg-alpha-white-2',
      'bg-alpha-white-4',
      'bg-alpha-white-6',
      'bg-alpha-white-8',
      'bg-alpha-white-10',
      'bg-alpha-white-12',
      'bg-alpha-white-16',
      'bg-alpha-white-24',
      'bg-alpha-white-40',
      'bg-alpha-white-56',
      'bg-alpha-white-64',
      'bg-alpha-white-72',
      'bg-alpha-white-80',
      'bg-alpha-white-88',
    ],
  },
  'alpha-black': {
    variants: [
      'bg-alpha-black-0',
      'bg-alpha-black-2',
      'bg-alpha-black-4',
      'bg-alpha-black-6',
      'bg-alpha-black-8',
      'bg-alpha-black-10',
      'bg-alpha-black-12',
      'bg-alpha-black-16',
      'bg-alpha-black-24',
      'bg-alpha-black-40',
      'bg-alpha-black-56',
      'bg-alpha-black-64',
      'bg-alpha-black-72',
      'bg-alpha-black-80',
      'bg-alpha-black-88',
    ],
  },
} as const;
